swagger: '2.0'
info:
  version: '1.0'
  title: lvdat Tools API
  contact: {}
host: localhost:8080
basePath: /api/youtube/video
securityDefinitions: {}
schemes:
- http
consumes:
- application/json
produces:
- application/json
paths:
  /{id}:
    get:
      summary: Get data of Youtube Video
      tags:
      - Youtube
      operationId: GetdataofYoutubeVideo
      deprecated: false
      produces:
      - application/json; charset=utf-8
      parameters:
      - name: id
        in: path
        required: true
        type: string
        description: ''
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/GetdataofYoutubeVideo'
          examples:
            application/json; charset=utf-8:
              thumbnail_height: 360
              url: https://www.youtube.com/watch?v=MqW1GMwiJ2I
              type: video
              height: 113
              provider_url: https://www.youtube.com/
              html: <iframe width="200" height="113" src="https://www.youtube.com/embed/MqW1GMwiJ2I?feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen title="NONSTOP VIỆT MIX 2020 | Nắng Ấm Xa Dần  (Viezd Remix)  | Nhạc Trẻ Remix Hay Nhất 2020"></iframe>
              author_name: Hoàng Nam Entertainment
              author_url: https://www.youtube.com/channel/UCtH6abm1YQlvM2zJqAZ8X6A
              thumbnail_url: https://i.ytimg.com/vi/MqW1GMwiJ2I/hqdefault.jpg
              title: NONSTOP VIỆT MIX 2020 | Nắng Ấm Xa Dần  (Viezd Remix)  | Nhạc Trẻ Remix Hay Nhất 2020
              width: 200
              thumbnail_width: 480
              provider_name: YouTube
              id: MqW1GMwiJ2I
              dateCreated: 2022-04-09T13:17:58.501025Z
              likes: 75961
              dislikes: 3160
              rating: 4.84024468851506
              viewCount: 12667934
              deleted: false
definitions:
  GetdataofYoutubeVideo:
    title: GetdataofYoutubeVideo
    example:
      thumbnail_height: 360
      url: https://www.youtube.com/watch?v=MqW1GMwiJ2I
      type: video
      height: 113
      provider_url: https://www.youtube.com/
      html: <iframe width="200" height="113" src="https://www.youtube.com/embed/MqW1GMwiJ2I?feature=oembed" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen title="NONSTOP VIỆT MIX 2020 | Nắng Ấm Xa Dần  (Viezd Remix)  | Nhạc Trẻ Remix Hay Nhất 2020"></iframe>
      author_name: Hoàng Nam Entertainment
      author_url: https://www.youtube.com/channel/UCtH6abm1YQlvM2zJqAZ8X6A
      thumbnail_url: https://i.ytimg.com/vi/MqW1GMwiJ2I/hqdefault.jpg
      title: NONSTOP VIỆT MIX 2020 | Nắng Ấm Xa Dần  (Viezd Remix)  | Nhạc Trẻ Remix Hay Nhất 2020
      width: 200
      thumbnail_width: 480
      provider_name: YouTube
      id: MqW1GMwiJ2I
      dateCreated: 2022-04-09T13:17:58.501025Z
      likes: 75961
      dislikes: 3160
      rating: 4.84024468851506
      viewCount: 12667934
      deleted: false
    type: object
    properties:
      thumbnail_height:
        type: integer
        format: int32
      url:
        type: string
      type:
        type: string
      height:
        type: integer
        format: int32
      provider_url:
        type: string
      html:
        type: string
      author_name:
        type: string
      author_url:
        type: string
      thumbnail_url:
        type: string
      title:
        type: string
      width:
        type: integer
        format: int32
      thumbnail_width:
        type: integer
        format: int32
      provider_name:
        type: string
      id:
        type: string
      dateCreated:
        type: string
      likes:
        type: integer
        format: int32
      dislikes:
        type: integer
        format: int32
      rating:
        type: number
        format: double
      viewCount:
        type: integer
        format: int32
      deleted:
        type: boolean
    required:
    - thumbnail_height
    - url
    - type
    - height
    - provider_url
    - html
    - author_name
    - author_url
    - thumbnail_url
    - title
    - width
    - thumbnail_width
    - provider_name
    - id
    - dateCreated
    - likes
    - dislikes
    - rating
    - viewCount
    - deleted
tags:
- name: Youtube